CC ?= cc
CFLAGS ?= -O2 -Wall -Wextra -std=c99
LDFLAGS ?=
LDLIBS ?= -lssl -lcrypto
WORKDIR ?= work

TARGET = $(WORKDIR)/spicebush
OBJS = $(WORKDIR)/spicebush_freebsd.o $(WORKDIR)/spicebush_shared.o $(WORKDIR)/spicebush_http_freebsd.o

all: $(TARGET)

$(WORKDIR):
	mkdir -p $(WORKDIR)

$(WORKDIR)/spicebush_freebsd.o: spicebush_freebsd.c spicebush_shared.h spicebush_http.h
	mkdir -p $(WORKDIR)
	$(CC) $(CFLAGS) -c spicebush_freebsd.c -o $@

$(WORKDIR)/spicebush_shared.o: spicebush_shared.c spicebush_shared.h
	mkdir -p $(WORKDIR)
	$(CC) $(CFLAGS) -c spicebush_shared.c -o $@

$(WORKDIR)/spicebush_http_freebsd.o: spicebush_http_freebsd.c spicebush_http.h spicebush_shared.h
	mkdir -p $(WORKDIR)
	$(CC) $(CFLAGS) -c spicebush_http_freebsd.c -o $@

$(TARGET): $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $(OBJS) $(LDLIBS)

clean:
	rm -f $(OBJS) $(TARGET)

.PHONY: all clean
